#!/usr/bin/env python3
"""Generate the issue forms in .github/ISSUE_TEMPLATE/: access-request.yml (join/leave a team) and new-team.yml.
Issue Forms cannot load options dynamically, so two lists are baked in:
  - teams: from access.yaml. CI runs --check to keep them in sync.
  - users: all org members, from GitHub (gh api). Refreshed with --users; --check ignores them, so a PR never fails
    because someone joined the org yesterday. .github/workflows/refresh-form.yml refreshes them on a schedule.
Usage: tools/gen-issue-form.py            # teams from access.yaml, users kept from the existing form
       tools/gen-issue-form.py --users    # also refresh users from GitHub (needs gh, env ORG or org: in access.yaml)
       tools/gen-issue-form.py --check    # exit 1 if the forms are out of sync (team list or structure)"""
import os, subprocess, sys
import yaml
from common import ROOT

DIR = os.path.join(ROOT, ".github", "ISSUE_TEMPLATE")
OUT = os.path.join(DIR, "access-request.yml")
OUT_TEAM = os.path.join(DIR, "new-team.yml")
HIDDEN = {"developers", "platform"}   # roster team, and the team that approves: membership there is decided by owners via PR
SELF = "Myself (the requester)"   # first option, preselected; the workflow swaps it for the issue author
HEADER = "# Generated by tools/gen-issue-form.py. Teams from access.yaml, users from the org (--users). Do not edit by hand.\n"

cfg = yaml.safe_load(open(os.path.join(ROOT, "access.yaml")))
teams = [(t.get("name") or slug, slug) for slug, t in (cfg.get("teams") or {}).items() if slug not in HIDDEN and t is not None]
team_options = [f"{name} ({slug})" if name != slug else slug for name, slug in sorted(teams, key=lambda x: x[0].lower())]

def existing_users():
    """User options from the access form already on disk, minus the SELF entry."""
    if not os.path.exists(OUT):
        return []
    for field in (yaml.safe_load(open(OUT, encoding="utf-8")) or {}).get("body") or []:
        if field.get("id") == "who":
            return [o for o in field["attributes"]["options"] if o != SELF]
    return []

def github_users():
    org = os.environ.get("ORG") or cfg.get("org")
    if not org:
        sys.exit("Set ORG=<github-org> or org: in access.yaml")
    out = subprocess.run(["gh", "api", f"orgs/{org}/members", "--paginate", "--jq", ".[].login"],
                         check=True, capture_output=True, text=True).stdout
    return sorted({l.strip() for l in out.splitlines() if l.strip()}, key=str.lower)

if "--users" in sys.argv:
    users = github_users()
else:
    users = existing_users()
    if not users and "--check" not in sys.argv:
        users = github_users()

def who(label, description):
    return {"type": "dropdown", "id": "who", "attributes": {"label": label, "description": description,
            "multiple": True, "options": [SELF] + users, "default": 0}}

def render_access(users):
    form = {
        "name": "Request team access",
        "description": "Add yourself or colleagues to a team, or remove. Creates a pull request that the platform team approves.",
        "title": "Access request",     # set automatically by the workflow from the choices, e.g. "Add octocat to Kunde A team"
        "labels": ["access-request"],
        "body": [
            {"type": "markdown", "attributes": {"value": "When you submit, a pull request against `access.yaml` is created automatically. "
                "Once approved and merged, access in GitHub updates by itself. See README.md for details.\n\n"
                "Leave the title as is. It is set automatically from your choices."}},
            {"type": "dropdown", "id": "action", "attributes": {"label": "Action", "options": ["Add", "Remove"]}, "validations": {"required": True}},
            {"type": "dropdown", "id": "team", "attributes": {"label": "Team", "options": team_options}, "validations": {"required": True}},
            who("Who", "You are preselected. Pick more to request on behalf of colleagues."),
            {"type": "textarea", "id": "reason", "attributes": {"label": "Reason", "description": "Which project, from when, for how long."}, "validations": {"required": True}},
        ],
    }
    return HEADER + yaml.safe_dump(form, sort_keys=False, allow_unicode=True, width=120)

def render_team(users):
    form = {
        "name": "Request a new team",
        "description": "A new customer that has no team yet. Creates a pull request that adds the team and its repos.",
        "title": "New team",           # set automatically by the workflow, e.g. "New team Kunde AS"
        "labels": ["new-team"],
        "body": [
            {"type": "markdown", "attributes": {"value": "One team per customer, with admin on the customer's repos. The team name is the full "
                "customer name; GitHub derives the slug from it (\"Kunde AS\" → `kunde-as`). Once the PR is approved and merged, the team exists "
                "and members can be added with the \"Request team access\" form.\n\nLeave the title as is."}},
            {"type": "input", "id": "name", "attributes": {"label": "Customer name", "description": "Full name, capitalised. Becomes the team name.",
                "placeholder": "e.g. Kunde AS"}, "validations": {"required": True}},
            {"type": "input", "id": "repos", "attributes": {"label": "Repos", "description": "Repo names or globs, comma-separated. A glob covers repos created later too.",
                "placeholder": "e.g. Kunde.*, kunde-website"}, "validations": {"required": True}},
            {"type": "dropdown", "id": "who", "attributes": {"label": "Members", "description": "Initial members. Leave empty to add people later with the access form.",
                "multiple": True, "options": [SELF] + users}},
            {"type": "textarea", "id": "reason", "attributes": {"label": "Reason", "description": "Which project, who is the tech lead."}, "validations": {"required": True}},
        ],
    }
    return HEADER + yaml.safe_dump(form, sort_keys=False, allow_unicode=True, width=120)

if "--check" in sys.argv:
    cur = existing_users()
    for path, render in ((OUT, render_access), (OUT_TEAM, render_team)):
        on_disk = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
        if on_disk != render(cur):
            sys.exit(f"{os.path.relpath(path, ROOT)} is out of sync with access.yaml or the generator. Run tools/gen-issue-form.py and commit.")
    print("issue forms in sync"); sys.exit(0)
os.makedirs(DIR, exist_ok=True)
open(OUT, "w", encoding="utf-8").write(render_access(users))
open(OUT_TEAM, "w", encoding="utf-8").write(render_team(users))
print(f"wrote access-request.yml ({len(team_options)} teams, {len(users)} users) and new-team.yml")
