#!/usr/bin/env python3
"""Generate .github/ISSUE_TEMPLATE/access-request.yml.
Issue Forms cannot load options dynamically, so two lists are baked in:
  - teams: from access.yaml. CI runs --check to keep them in sync.
  - users: all org members, from GitHub (gh api). Refreshed with --users; --check ignores them, so a PR never fails
    because someone joined the org yesterday. .github/workflows/refresh-form.yml refreshes them on a schedule.
Usage: tools/gen-issue-form.py            # teams from access.yaml, users kept from the existing form
       tools/gen-issue-form.py --users    # also refresh users from GitHub (needs gh, env ORG or org: in access.yaml)
       tools/gen-issue-form.py --check    # exit 1 if the team list is out of sync"""
import os, subprocess, sys
import yaml
from common import ROOT

OUT = os.path.join(ROOT, ".github", "ISSUE_TEMPLATE", "access-request.yml")
HIDDEN = {"developers"}          # roster-only team; nobody requests membership there
SELF = "Myself (the requester)"   # first option, preselected; the workflow swaps it for the issue author

cfg = yaml.safe_load(open(os.path.join(ROOT, "access.yaml")))
teams = [(t.get("name") or slug, slug) for slug, t in (cfg.get("teams") or {}).items() if slug not in HIDDEN and t is not None]
team_options = [f"{name} ({slug})" if name != slug else slug for name, slug in sorted(teams, key=lambda x: x[0].lower())]

def existing_users():
    """User options from the form already on disk, minus the SELF entry."""
    if not os.path.exists(OUT):
        return []
    for field in (yaml.safe_load(open(OUT, encoding="utf-8")) or {}).get("body") or []:
        if field.get("id") == "who":
            return [o for o in field["attributes"]["options"] if o != SELF]
    return []

def github_users():
    org = os.environ.get("ORG") or cfg.get("org")
    if not org:
        sys.exit("Set ORG=<github-org> or org: in access.yaml")
    out = subprocess.run(["gh", "api", f"orgs/{org}/members", "--paginate", "--jq", ".[].login"],
                         check=True, capture_output=True, text=True).stdout
    return sorted({l.strip() for l in out.splitlines() if l.strip()}, key=str.lower)

if "--users" in sys.argv:
    users = github_users()
else:
    users = existing_users()
    if not users and "--check" not in sys.argv:
        users = github_users()

def render(users):
    form = {
        "name": "Request team access",
        "description": "Add yourself or colleagues to a team, or remove. Creates a pull request that the platform team approves.",
        "title": "Access request",     # set automatically by the workflow from the choices, e.g. "Add octocat to Kunde A team"
        "labels": ["access-request"],
        "body": [
            {"type": "markdown", "attributes": {"value": "When you submit, a pull request against `access.yaml` is created automatically. "
                "Once approved and merged, access in GitHub updates by itself. See FLOW.md for details.\n\n"
                "Leave the title as is. It is set automatically from your choices."}},
            {"type": "dropdown", "id": "action", "attributes": {"label": "Action", "options": ["Add", "Remove"]}, "validations": {"required": True}},
            {"type": "dropdown", "id": "team", "attributes": {"label": "Team", "options": team_options}, "validations": {"required": True}},
            {"type": "dropdown", "id": "who", "attributes": {"label": "Who", "description": "You are preselected. Pick more to request on behalf of colleagues.",
                "multiple": True, "options": [SELF] + users, "default": 0}},
            {"type": "textarea", "id": "reason", "attributes": {"label": "Reason", "description": "Which project, from when, for how long."}, "validations": {"required": True}},
        ],
    }
    return ("# Generated by tools/gen-issue-form.py. Teams from access.yaml, users from the org (--users). Do not edit by hand.\n"
            + yaml.safe_dump(form, sort_keys=False, allow_unicode=True, width=120))

text = render(users)
if "--check" in sys.argv:
    cur = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
    if cur != render(existing_users()):
        sys.exit("The issue form is out of sync with access.yaml. Run tools/gen-issue-form.py and commit.")
    print("issue form in sync"); sys.exit(0)
os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "w", encoding="utf-8").write(text)
print(f"wrote {os.path.relpath(OUT, ROOT)} with {len(team_options)} teams and {len(users)} users")
