#!/usr/bin/env python3
"""Generate a restructured access.yaml: one client-<slug> team per active customer (from clients.yaml),
members = employees who committed to the customer's active repos in the snapshot's activity window.
--phase 1 (default) is additive: developers keeps write on *, legacy teams and employees' direct grants are kept
verbatim, so tools/plan.py only proposes creations and grants. --phase 2 drops all of that.
Usage: tools/restructure.py [--snapshot file] [--clients clients.yaml] > access.yaml"""
import argparse, fnmatch, os, re, sys, unicodedata
from collections import Counter, defaultdict
import yaml
from common import ROOT, RANK, load_snapshot, actual_state, slugify

ap = argparse.ArgumentParser()
ap.add_argument("--snapshot"); ap.add_argument("--clients", default=os.path.join(ROOT, "clients.yaml"))
ap.add_argument("--phase", type=int, choices=[1, 2], default=1,
                help="1 = additive: keep developers write *, legacy teams and employees' direct grants. 2 = remove them.")
args = ap.parse_args()
snap = load_snapshot(args.snapshot)
act = actual_state(snap)
clients = yaml.safe_load(open(args.clients))
members, owners, outside = set(snap["members"]), set(snap["owners"]), set(snap["outside"])
is_employee = lambda u: u in members and "[bot]" not in u and not u.startswith("~")

# Role a customer team gets on its repos. admin (not write) because Actions secrets/variables and environments
# can only be managed by repo admins. Blast radius is limited by org settings and org rulesets, see README.
TEAM_ROLE = "admin"

def matches(name, globs):
    return any(fnmatch.fnmatchcase(name.lower(), g.lower()) for g in globs or [])

active = [r for r in snap["repos"] if r["active"] and not r["archived"]]
by_client, unmatched = defaultdict(list), []
internal_globs = (clients.get("internal") or {}).get("match") or []
exclude_globs = clients.get("exclude") or []          # repos whose grants are written by hand in access.yaml (e.g. github-access)
for r in active:
    if matches(r["name"], exclude_globs):
        continue
    hit = [slug for slug, c in clients["clients"].items() if matches(r["name"], c.get("match"))]
    if len(hit) > 1:
        sys.exit(f"{r['name']} matches several customers: {hit}")
    if hit:
        by_client[hit[0]].append(r)
    elif matches(r["name"], internal_globs):
        by_client["__internal__"].append(r)
    else:
        unmatched.append(r["name"])

def team_from_repos(repos):
    """members from commit activity on these repos. No maintainers: access changes go through the request flow,
    and owners are implicit maintainers of every team."""
    commits = Counter()
    for r in repos:
        for c in r["committers"]:
            if is_employee(c["login"]):
                commits[c["login"]] += c["commits"]
    return sorted(commits), commits

def dump(obj, indent=0):
    text = yaml.safe_dump(obj, sort_keys=False, allow_unicode=True, width=120, default_flow_style=False)
    return "".join(" " * indent + l + "\n" for l in text.rstrip("\n").split("\n"))

out = []
out.append(f"# Desired access state for {snap['org']}. Source of truth. Changed via PR; applied with tools/apply.py.")
out.append(f"# Generated by tools/restructure.py from snapshot {snap['generated_at']} (activity window {snap['activity_days']} days) and clients.yaml.")
out.append("# Model: everyone has read via base permission. Admin only via one team per customer (name = full customer name) on the customer's active repos, and the internal team on internal repos.")
out.append("# Dormant repos (no push in the window) have no team grants. Direct collaborators only for externals.")
if unmatched:
    out.append("# TODO active repos without a customer in clients.yaml (get no write): " + ", ".join(sorted(unmatched)))
out.append(dump({"org": snap["org"], "base_permission": "read", "owners": sorted(owners)}))
out.append("teams:")

# developers: roster only
dev = act["teams"].get("developers", {"members": set(), "maintainers": set()})
dev_entry = {"description": "All developers. Read only (via base permission); write is granted per customer in customer teams.",
             "privacy": "secret", "members": sorted(dev["members"])}
if args.phase == 1:
    dev_entry["repos"] = {"write": ["*"]}
text = dump({"developers": dev_entry}, 2)
if args.phase == 1:
    text = text.replace("    repos:\n", "    repos:  # PHASE 2: remove this block. Then developers only have read.\n")
out.append(text)

# client teams: key = slug derived from the full name, e.g. "Kunde A" -> kunde-a
merged = set()
team_slugs = {}
for ckey in sorted(by_client):
    if ckey == "__internal__":
        continue
    repos = by_client[ckey]
    name = clients["clients"][ckey].get("name") or ckey
    slug = slugify(name)
    if slug in team_slugs:
        sys.exit(f"two customers give the same team slug '{slug}': {team_slugs[slug]} and {ckey}")
    team_slugs[slug] = ckey
    mem, commits = team_from_repos(repos)
    entry = {"name": name, "description": name}
    members_set, grants = set(mem), {r["name"]: TEAM_ROLE for r in repos}
    existing = act["teams"].get(slug)
    maintainers = set()
    if existing:                                   # same slug already in GitHub: take it over; phase 1 never lowers anything it has
        merged.add(slug)
        members_set |= existing["members"]
        maintainers |= existing["maintainers"]     # existing explicit maintainers are kept, none are proposed
        if args.phase == 1:
            for repo, role in existing["repos"].items():
                if RANK.get(role, 0) > RANK.get(grants.get(repo, "none"), 0):
                    grants[repo] = role
    if maintainers:
        entry["maintainers"] = sorted(maintainers)
    entry["members"] = sorted(members_set - maintainers)
    by_role = defaultdict(list)
    for repo, role in grants.items():
        by_role[role].append(repo)
    entry["repos"] = {role: sorted(names) for role, names in sorted(by_role.items(), key=lambda kv: -len(kv[1]))}
    text = dump({slug: entry}, 2)
    if existing:
        text = text.replace(f"  {slug}:\n", f"  {slug}:  # existing team, taken over as customer team\n", 1)
    if not mem:
        text = text.replace("    members: []\n", "    members: []  # TODO no employees committed in the window\n")
    out.append(text)

# internal
internal_repos = by_client.get("__internal__", [])
out.append(dump({"internal": {
    "name": "Internal",
    "description": "Internal repos: packages, tools, experiments.",
    "members": sorted(dev["members"]),
    "repos": {TEAM_ROLE: sorted(r["name"] for r in internal_repos)}}}, 2))

# legacy teams, verbatim, removed in phase 2
legacy = sorted(s for s in act["teams"] if s != "developers" and s not in merged) if args.phase == 1 else []
if legacy:
    out.append("  # --- PHASE 2: remove the legacy teams below once the customer teams are verified (gap = 0 in the report) ---")
    for slug in legacy:
        t = act["teams"][slug]
        entry = {}
        if t["description"]: entry["description"] = t["description"]
        if t["privacy"] != "closed": entry["privacy"] = t["privacy"]
        if t["maintainers"]: entry["maintainers"] = sorted(t["maintainers"])
        entry["members"] = sorted(t["members"] - t["maintainers"])
        by_role = defaultdict(list)
        for repo, role in t["repos"].items():
            by_role[role].append(repo)
        if by_role:
            entry["repos"] = {role: (["*"] if set(names) == act["all_repos"] else sorted(names)) for role, names in sorted(by_role.items(), key=lambda kv: -len(kv[1]))}
        out.append(dump({slug: entry}, 2))

# direct collaborators: externals only
direct = {}
for repo in sorted(act["direct"]):
    cols = {u: role for u, role in sorted(act["direct"][repo].items()) if u in outside or args.phase == 1}
    if cols:
        direct[repo] = {"collaborators": cols}
if args.phase == 1:
    out.append("# Direct collaborators. PHASE 2: remove employees here (tools/plan.py warns about each), keep externals only.")
else:
    out.append("# Direct collaborators: externals only (outside collaborators). Employees get access via teams.")
text = dump({"repos": direct})
if args.phase == 1:
    for repo, spec in direct.items():
        for u, role in spec["collaborators"].items():
            if u in members:
                text = text.replace(f"      {u}: {role}\n", f"      {u}: {role}  # employee, PHASE 2: remove\n", 1)
out.append(text)
print("\n".join(out))
